# Generated by Django 5.0.2 on 2024-02-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='short_description',
            new_name='short_intro',
        ),
    ]
